version: '3'

services:
  mongodb:
    image: mongo
    restart: always
    volumes:
      - data:/data/db
    ports:
      - "27017:27017"
    env_file:
      - ./docker.env
  redis:
    image: redis:7.2-alpine3.18
    restart: always
    volumes:
      - cache:/data
    ports:
      - "6379:6379"
  server:
    image: phuctq32/pro-magnet
    ports:
      - "8080:8080"
    env_file:
      - ./docker.env
    environment:
      - ENV=production
    depends_on:
      - mongodb
      - redis

volumes:
  data:
  cache: